### ISSUE TITLE
Compatibility with PHP 7.1

### ISSUE THREAD

**Issue by Amunak** [mll-lab/graphql-php-scalars#13]
Why did you remove compatibility with 7.1 when the parent project still provides it until v. 15?

It's not like you use any of the features (of which there is basically just the `object` type).

Like sure, PHP 7.1 is *technically* no longer supported, but it's still used by many projects, and it's beyond stupid to not support the same versions as the library you are extending.

**Comment by spawnia** [comment]
I suggest you take a long hard look at yourself and reconsider your attitude. Insulting maintainers of free open source software is not a good look.

**Comment by Amunak** [comment]
Did my completely generic statement that wasn't aimed at anybody offend you? Granted I wasn't *nice* but that's it. You could've shut me down with literally any on-topic response and move on, but no.

I suggest you get off your high horse and respond to the issue at hand, closing tickets with completely off-topic comments is not a good look for a maintainer of free open source software.
