### ISSUE TITLE
Simplified type usage

### ISSUE THREAD

**Issue by aimeos** [mll-lab/graphql-php-scalars#24]
Currently, you have to use a type registry to create types only once. The graphql-php package offers simple registration of scalar types only once by using static getter methods:

https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/Type.php#L28-L69

The code for the `Email` static getter could be:

```php
    protected static $object;

    public static function type(): ScalarType
    {
        return static::$object ??= new Email();
    }
```

and invocation would be simply `Email::type()`.
Are you interested in a PR adding the `type()` methods for type classes?

**Comment by spawnia** [comment]
I will not add such a method because scalars can be configured in different ways through the options passed in the constructor. A method that returns a singleton would give the wrong impression that all instances of the scalar are alike.
