### ISSUE TITLE
JSON format in query

### ISSUE THREAD

**Issue by SimonErich** [mll-lab/graphql-php-scalars#29]
Hey,

I have been trying to use the JSON scalar in our project.
I have the following query:
```mutation {
  getTimeDetails(input: { 
      filters: [
          {key: "timeframeStart", value: "2023-01-01" },
          {key: "timeframeEnd", value: "2023-02-01" },
      ]
    }) {
    data {
      label
      color
      spots {
        key
        value
      }
    } 
  }
}
```

But I keep getting the error:
```
{
  "errors": [
    {
      "message": "Can not parse literals without a value: { timeframeStart: { value: \"2023-01-01\" }, timeframeEnd: { value: \"2023-02-01\" } }.",
      "extensions": {
        "file": "/home/vagrant/Code/ontime-api/src/vendor/mll-lab/graphql-php-scalars/src/JSON.php",
        "line": 29
      }
    }
  ]
}
```

My properties do have values. Or does the JSON scalar expect a nested object or different structure here?
Unfortunately I can't really find out if the problem is related to my implementation or the package itself.
As far as I can tell the format should be correct.

Maybe, if a special format or nesting for JSON is needed it would be good to add to documentation.

**Comment by spawnia** [comment]
The JSON scalar expects a string in JSON format, I don't see you passing that.

**Comment by spawnia** [comment]
See https://github.com/mll-lab/graphql-php-scalars/commit/afc65e66d2b58c0af48101cd85a86bc5e2730c65

**Comment by SimonErich** [comment]
Ah, that makes so much more sense and works now. Sorry, I thought you could pass an object.
Thanks for clarifying in the docs as well! Nice work! 👍
