### ISSUE TITLE
ScalarType JSON: json array cannot parsed

### ISSUE THREAD

**Issue by boehlim377** [mll-lab/graphql-php-scalars#30]
If an array is contained in a JSON variable instead of a JSON string, a type error is thrown.

Possible solution: change the parseValue function and add a type check:

public function parseValue($value)
{
    if (is_string($value)) {
        return $this->decodeJSON($value);
    }
    return $value;
}

**Comment by spawnia** [comment]
As described in https://github.com/mll-lab/graphql-php-scalars#json, you will have to provide a JSON string for values of this type.
