### ISSUE TITLE
How to receive a JSON with GraphQL in Laravel? I tried using Mixed Scalar Type in args but received error

### ISSUE THREAD

**Issue by viniciusls** [mll-lab/graphql-php-scalars#5]
Hi all,

I have the following code on a Vue.js component that uses Apollo to call a Laravel application with GraphQL installed (using the package: https://github.com/rebing/graphql-laravel):

```
const INVITES_QUERY = gql`
  query INVITES_QUERY {
    invites(limit: 75, page: 1, orderBy: { field: ID, direction: DESC }) {
      id
      email
      status
    }
  }
`;

 export default {
   name: 'MyInvites',
   components: { InviteTable },
   apollo: {
      invites: INVITES_QUERY
   },
... Continue
```

In order to be able to receive the `orderBy` argument (which is a JSON object) from this GraphQL query, in my `InvitesQuery.php` I used a `new Mixed()` (from package https://github.com/mll-lab/graphql-php-scalars) as the type of the argument:

```
<?php

namespace App\GraphQL\Queries;

use App\Invite;
use GraphQL\Type\Definition\Type;
use Illuminate\Support\Facades\Auth;
use MLL\GraphQLScalars\Mixed;
use Rebing\GraphQL\Support\Facades\GraphQL;
use Rebing\GraphQL\Support\Query;

class InvitesQuery extends Query
{
    protected $attributes = [
        'name' => 'invites',
    ];

    public function type(): Type {
        return Type::listOf(GraphQL::type('Invite'));
    }

    public function args(): array
    {
        return [
            'limit' => ['name' => 'limit', 'type' => Type::int()],
            'orderBy' => ['name' => 'orderBy', 'type' => new Mixed()],
            'page' => ['name' => 'page', 'type' => Type::int()]
        ];
    }

    public function resolve($root, $args) {
        if (!Auth::user()) {
            throw new \Error('User not authenticated', 403);
        }

        return Invite::where('friend_id', Auth::user()->id)
            ->orderBy($args['orderBy']['field'], $args['orderBy']['direction'])
            ->paginate($args['limit'], ['*'], 'page', $args['page']);
    }
}
```

The thing is that `'orderBy' => ['name' => 'orderBy', 'type' => new Mixed()]`, worked well, if I only have one Query using this type of argument. Of course I don't have only one Query that needs pagination, so I have another one with the exactly same args method and this gave me the following error everytime I run any GraphQL query:

```
GraphQL\Error\InvariantViolation: Schema must contain unique named types but contains multiple types named "Mixed"
```

If I remove the second Query that uses this `'orderBy' => ['name' => 'orderBy', 'type' => new Mixed()]`, the first one works normally. If I enable the second one again, all of them stop working with this error. I understood that this error describes that there are two things using the same type Mixed, but I don't know why this is wrong and how to fix that, as in both queries I need to receive this JSON from the front-end to be used in my query pagination. I tried using `Mixed::class` instead of `new Mixed()` but it never works, while `new Mixed()` works for one.

I appreciate any help with this issue. Thank you!

**Comment by viniciusls** [comment]
I was able to use **Mixed** type in more than one place by using a singleton like this:

```
<?php

namespace App\GraphQL\Types;

use MLL\GraphQLScalars\Mixed;

abstract class MixedType
{
    private static $mixedType;

    static function get() {
        if (!self::$mixedType) {
            self::$mixedType = new Mixed();
        }

        return self::$mixedType;
    }
}
```

And changing the query to use it like that:

```
'orderBy' => ['name' => 'orderBy', 'type' => MixedType::get()],
```

What do you think about this solution?

**Comment by spawnia** [comment]
The issue you are experiencing does arise from the underyling `webonyx/graphql-php` library. Using a singleton is fine, you can also go with a type registry: https://webonyx.github.io/graphql-php/type-system/#type-registry
